Vagrant.configure(2) do |config|
	config.vm.define "controller" do |worker|
	worker.vm.allow_hosts_modification = true
	worker.vm.hostname = "controller"
	worker.vm.box = "bionic64"
		worker.vm.network "private_network", ip: "10.0.3.10",
		   virtualbox__intnet: "Network1"
		worker.vm.provision "shell", path: "../scripts/install.sh"
		worker.vm.provider "virtualbox" do |v|
		  v.name = "controller"
		  v.memory = 1024
		  v.cpus = 1
		end
    end
end