---
apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  selector:
    app: hello-python
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
    nodePort: 30900
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellopython
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-python
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
        - name: hello-python
          image: omerlin/mypythontest:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-port
              containerPort: 5000
